services:
  web:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    networks:
      - net_homepage

networks:
  net_homepage:
    name: net_homepage
